### ISSUE TITLE
Non-nested docstrings do not fold

### ISSUE THREAD

**Issue by skupjoe** [tmhedberg/SimpylFold#106]
I often make copies of definition blocks when I code and use docstrings/multiline comments to comment out the old ones.

This does not fold:
![image](https://user-images.githubusercontent.com/5000412/46252593-90f7f680-c41f-11e8-8bfb-6cc8861ade89.png)

But if I add the docstring below the "def" line then it works:
![image](https://user-images.githubusercontent.com/5000412/46252644-7eca8800-c420-11e8-9361-ce4f90fa7a6a.png)

![image](https://user-images.githubusercontent.com/5000412/46252646-84c06900-c420-11e8-9975-a31a70cb1af5.png)

Please let me know if this is dependent on some setting. Otherwise, please consider supporting this type of folding.

Thank you.

**Comment by skupjoe** [comment]
For comparison, Notepad++ handles this just fine:

![image](https://user-images.githubusercontent.com/5000412/46252813-0b764580-c423-11e8-9405-81198d187e61.png)

**Comment by tmhedberg** [comment]
[PEP 257](https://www.python.org/dev/peps/pep-0257/#id15) defines a docstring as "a string literal that occurs as the first statement in a module, function, class, or method definition". What you have in the first image is not a docstring by that definition, therefore we don't intend to fold it.

If you're asking for all multi-line strings to be folded, regardless of where they appear, the simple answer is that it's probably not going to happen. The purpose of this plugin is to fold class and function definitions; other fold types have been added, but I'm generally not in favor of it because everyone in the world has their own unique opinion of what should and should not be folded, and if we implemented all of them, the plugin would explode in complexity. If you want to try to convince me that this particular feature is worthwhile, the most effective way would be to send a patch that implements it.
