### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by evprkr** [tmhedberg/SimpylFold#131]
Would it be possible to make this work with other languages? If it's something as easy as tweaking some settings, I'd be happy to do that myself.

Specifically, I'd like to see this work with C. I think it should be simple enough to recognize a fold by the area between opening and closing braces.

_Fig. 1 (unfolded)_
```
void SomeFunction(foo) {
    return "bar";
}
```

_Fig. 2 (folded)_
```
void SomeFunction(foo) { ... }
```

**Comment by tmhedberg** [comment]
Vim's default syntax definition for C includes folding directives, so you can just `:set foldmethod=syntax` and get something close to what you're looking for without any plugin.

This plugin is specifically built for Python and makes no real attempt to be generalizable to other languages. C's brace-delimited syntax is a lot different from Python's indentation-based syntax, so it would take a significant revamp to add support for C. I don't really think that would be worthwhile, since Vim can fold C code reasonably well out of the box.
