### ISSUE TITLE
Multi-line Strings

### ISSUE THREAD

**Issue by qguv** [tmhedberg/SimpylFold#22]
SimpylFold doesn't properly handle multi-line strings, especially important in test-driven development.

For example:

```python
    def testIndexToCoord(self):
        m = '''Wrong coordinate given from index. Check indexToCoord() method.

Index given: {}
Observed coordinate: {}
Expected coordinate: {}'''
        index = 3
        expectedCoord = (0, 1)
```

becomes

```python
+--  2 lines: def testIndexToCoord(self):--------------------------------------------------------------

Index given: {}
Observed coordinate: {}
Expected coordinate: {}'''
        index = 3
        expectedCoord = (0, 1)
```

**Comment by mgedmin** [comment]
A workaround that I use is to wrap the multi-line string in [textwrap.dedent()](https://docs.python.org/2/library/textwrap.html#textwrap.dedent):
```python
    def testIndexToCoord(self):
        m = textwrap.dedent('''\
            Wrong coordinate given from index. Check indexToCoord() method.

            Index given: {}
            Observed coordinate: {}
            Expected coordinate: {}''')
        index = 3
        expectedCoord = (0, 1)
```

**Comment by tmhedberg** [comment]
Reliably detecting this kind of case without actually implementing a full Python parser in Vim would be difficult if not impossible. This kind of edge case is pretty much always going to trip up the folding algorithm. It is a legitimate bug, but it's not likely to be fixed, because it would require an overhaul to how the plugin works, making it much more complicated. The existing algorithm is simple, pretty fast, and "good enough" in most cases, but will never be perfect.
