### ISSUE TITLE
SimpylFold breaks when re-opening a file in a different tab

### ISSUE THREAD

**Issue by OptiverTimAll** [tmhedberg/SimpylFold#27]
Steps to reproduce:

1. Create a Python file, `test.py`:

        def test():
            pass

2. Create some other file, `test.txt`:

        test text

3. Open `test.py` in Vim with SimpylFold installed. The `test()` function should be folded, and setting 'foldcolumn' to a non-zero value will reveal the extent of the fold.
4. Open `test.txt` in a new tab: `:tab sp test.txt`
5. Close the tab with `test.py` in it: `gT:q`
6. Open `test.py` in another new tab: `:tab sp test.py`

Expected result:

`test.py` appears with the `test()` function folded; 'foldcolumn` shows the extent of the fold.

Actual result:

`test.py` appears with no folding; 'foldcolumn' shows that no fold exists.

Notes:

* This works properly if I manually `:unlet b:loaded_SimpylFold` and then reload the file with `:e`.
* This also works properly if I use windows (`:sp`) instead of tabs (`:tab sp`). I'm not sure why, though, and I prefer tabs to maximize vertical space.
* The documentation for 'foldmethod' says that it's a per-window option, so I would imagine the `loaded_SimpylFold` flag should be window-local (`w:`) rather than buffer-local (`b:`).

**Comment by tmhedberg** [comment]
Unfortunately, making `loaded_SimpylFold` window-local isn't enough to fix this. You still have to `:e` the file again in the second tab in order for Vim to re-execute the SimpylFold script.

This is because ftplugins like this one are only executed when the buffer is initially created and its filetype is detected. When you close `test.py` in the first tab and then reopen it, it's reusing the same buffer as before, so the ftplugin isn't run again.

Probably the only way around this is to simply avoid setting window-local options like `'foldexpr'` and `'foldmethod'` from within an ftplugin. That would mean users of SimpylFold have to add an autocommand to `.vimrc` to set those options when loading a Python buffer:

```vim
autocmd BufWinEnter *.py setlocal foldexpr=SimpylFold(v:lnum) foldmethod=expr
autocmd BufWinLeave *.py setlocal foldexpr< foldmethod<
```

I'll leave the options in the plugin script since it works automatically for some cases, but to fix situations like your example, you'll have to add lines like the above to `.vimrc`.

**Comment by OptiverTimAll** [comment]
For the benefit of the archives, it looks like I worked around this problem in my local copy by just deleting the `if exists('b:loaded_SimpylFold')` check entirely, so SimpylFold would always run regardless. This is probably wasteful of resources, but the hosts where I typically run Vim are fast enough that I don't notice in practice.

Thanks for taking the time to look into my report!
