### ISSUE TITLE
commented out lines break folding

### ISSUE THREAD

**Issue by reckoner** [tmhedberg/SimpylFold#8]
Hi,

Given,

```
 class Foo:
```
# commented line with hash mark in column 1

```
     pass
```

breaks the folding behavior on `Foo`. The hash character is in column 1. GIthub's markdown seems to be mangling this. Is there a way to get it to automatically fold even if there are such comment lines in the block.

Thanks!

**Comment by mgedmin** [comment]
I have a habit of temporarily commenting out bits of code like this while I'm debugging stuff:

```python
def somefunc(...):
    do_this()
##  do_that()
    do_this_again()
```

I like it because it doesn't change the indentation of the commented-out code, and because it's easy to comment/uncomment in vim with `0R##<esc>` or `0R<space><space><esc>`.  (The hash-mark is doubled to make it explicit that this is a bit of temporarily-commented-out code, and not a real comment.)

I never commit commented-out code, so I don't consider it a PEP-8 violation ;)

Anyway, if I switch to SimpylFold instead of [my hacky foldexpr](https://github.com/mgedmin/dotvim/blob/master/syntax/python.vim), I'll have to see if I can create a patch for this.
